# Exercises week 43 and 44
### The OR, AND, and XOR gates

We have two input values $x_1$ and $x_2$ which decide the output from the two types of gates. Since each input value can be either 0 or 1 we can write the input as a design matrix $X$ where the first and second column represents $x_1$ and $x_2$ respectively as:
$$X = \begin{bmatrix} 0 & 0 \\ 0 & 1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$$

The output $y$ for the different gates we can write as the vectors $y^T=[0, 1,1,1]$ for the OR gate, $y^T=[0,0,0,1]$ for the AND gate, and $y^T=[0, 1, 1, 0]$ for the XOR gate. We setup this matrix and these vectors:


In [462]:
import numpy as np
import jax.numpy as jnp
from jax import grad

# Set up design matrix and output vectors
X = np.asarray([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Gate target arrays
yOR = np.asarray([0, 1, 1, 1]).reshape(-1, 1)
yAND = np.asarray([0, 0, 0, 1]).reshape(-1, 1)
yXOR = np.asarray([0, 1, 1, 0]).reshape(-1, 1)

We create our NN architecture with the Sigmoid function $\sigma$ as activation function where
\begin{equation}
    \sigma(x) = \frac{1}{1+e^{-x}}
\end{equation}
as such

In [463]:
# Parameters
n_hidden_nodes = 2  # hidden nodes per layer
n_categories = 1  # output nodes
n_inputs, n_features = X.shape  # 2 inputs, 4 features
target_gate = "XOR"  # choose which target gate to train on


# Activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


# Initialize random number generator with seed
rng = np.random.default_rng(2023)

# Weights and bias in the hidden layer
hidden_weights = rng.standard_normal((n_features, n_hidden_nodes))  # weights normally distributed
hidden_bias = np.zeros(n_hidden_nodes) + 0.01

# Weights and bias in the output layer
output_weights = rng.standard_normal((n_hidden_nodes, n_categories))  # weights normally distributed
output_bias = np.zeros(n_categories) + 0.01


print("Before back propagation:\n")
print("Output weights and bias:")
print(output_weights)
print(output_bias)

print()
print("Hidden weights and bias:")
print(hidden_weights)
print(hidden_bias)

Before back propagation:

Output weights and bias:
[[-0.77586755]
 [ 0.8087058 ]]
[0.01]

Hidden weights and bias:
[[ 0.60172129  1.15161897]
 [-1.35946236  0.22205533]]
[0.01 0.01]


### Feed forward
Then we set up the feed forward algorithm and compare one pass with the target vectors $y^T$

In [464]:
# Get the chosen target array
if target_gate == "OR":
    target = yOR
elif target_gate == "AND":
    target = yAND
elif target_gate == "XOR":
    target = yXOR
else:
    raise ValueError(f"Target gate not found ('{target_gate}').")

In [465]:
def feed_forward(X):
    """Feed forward algorithm for one hidden layer"""
    # Weighted sum of inputs to the hidden layer
    z_h = X @ hidden_weights + hidden_bias

    # Activation in the hidden layer
    a_h = sigmoid(z_h)

    # Weighted sum of inputs to the output layer
    z_o = a_h @ output_weights + output_bias

    # Axis 0 holds each input and axis 1 the probabilities of each category
    probabilities = sigmoid(z_o)  # this is a_o
    return z_h, a_h, z_o, probabilities


@np.vectorize
def predict(probability):
    """Get prediction from array with floats."""
    if probability < 0.5:
        return 0
    else:
        return 1


# Make prediction and compare with gate target y_vectors
z_h, a_h, z_o, probabilities = feed_forward(X)
predictions = predict(probabilities)

print("Target:")
print(target)

print("\nProbabilities:")
print(probabilities)

print("\nPrediction:")
print(predictions)

Target:
[[0]
 [1]
 [1]
 [0]]

Probabilities:
[[0.50662492]
 [0.5747513 ]
 [0.53068917]
 [0.60044713]]

Prediction:
[[1]
 [1]
 [1]
 [1]]


We see this prediction does not match any target. This is because we only did one pass and that was with random starting weights. Now we setup the cost function and the back propagation algorithm.

<!--- 
For the cost function we use the cross entropy for binary classification given as
$$C(\boldsymbol{\theta}) = -\sum_{i=1}^n \left( y_i \ln [p(y_i | x_i, \boldsymbol{\theta)}] + (1-y_i)\ln[1-p(y_i | x_i, \boldsymbol{\theta)}] \right)$$

where the probabilities $p$ we have from the sigmoid function 
$$p(y_i=1|x_i, \boldsymbol{\theta}) = \frac{\exp(\theta_0 + \theta_1 x_i)}{1- \exp(\theta_0 + \theta_1 x_i)}$$
$$p(y_i=0|x_i, \boldsymbol{\theta}) = 1 - p(y_i=1|x_i, \boldsymbol{\theta})$$ 
-->

For the cost function we use the cross entropy for binary classification given as
$$C(\boldsymbol{W}) = -\sum_{i=1}^n \left( t_i \log a_i^L + (1-t_i)\log(1-a_i^L) \right)$$
where $t$ is the target and $a^L$ is the final activation from the final/output layer.

In [466]:
def cost_log_reg(target):
    """Returns a function for the logistic cross entropy for binary classification / log loss function using a given target vector."""
    d = 1e-9  # small value to avoid infinities

    def func(x):
        #     return -(1 / target.size) * jnp.sum(target * jnp.log(x + d))
        #     return -np.sum(target * jnp.log(x + d) + (1 - target) * jnp.log(1 - x + d))
        return -jnp.sum(
                (target * jnp.log(x + d)) + ((1 - target) * jnp.log(1 - x + d))
        )

    return func


cost_func = cost_log_reg(target)
cost_func(predictions)

Array(41.446533, dtype=float32)

### Calculating the analytical gradients for back propagation
We differentiate the cost function with regards to (wgt) the activation of the output layer $a_i^L$ and get:
\begin{align*}
    \frac{\partial C}{\partial a_i^L} &= -\frac{\partial}{\partial a_i^L}(t_i \ln(a_i^L) + (1-t_i)\ln(1-a_i^L))
    \\ &= -(\frac{t_i}{a_i^L} + \frac{1-t_i}{1-a_i^L}(-1))
    \\ &= \frac{1-t_i}{1-a_i^L} - \frac{t_i}{a_i^L}
    \\ &= \frac{a_i^L(1-t_i)}{a_i^L(1-a_i^L)} - \frac{t_i(1-a_i^L)}{a_i^L(1-a_i^L)}
    \\ &= \underline{\frac{a_i^L-t_i}{a_i^L(1-a_i^L)}}
\end{align*}

The expression for the output error $\delta^L$ is 

\begin{equation}
    \delta_i^L = \sigma'(z_i^L)\frac{\partial C}{\partial a_i^L}
\end{equation}

where $\sigma$ is our Sigmoid function, we can differentiate it to be

\begin{equation}
    \sigma'(x) = \frac{e^{-x}}{(1+e^{-x})^2}
\end{equation}
which gives the following when putting in $a_i^L=\sigma(a_i^L)=1/(1+e^{-z_i^L})$:
\begin{gather*}
    \sigma'(z_i^L) &= \frac{e^{-z_i^L}}{(1+e^{-z_i^L})^2}
    \\ &= \left( \frac{1}{a_i^L} - 1 \right) (a_i^L)^2
    \\ &= \underline{a_i^L(1-a_i^L)}
\end{gather*}

which gives 
\begin{align*}
    \delta_i^L &= a_i^L(1-a_i^L)\ \frac{a_i^L-t_i}{a_i^L(1-a_i^L)}
    \\ &= \underline{a_i^L-t_i}
\end{align*}

such that our gradient for updating the weights will be:
\begin{equation}
    \nabla^L=\delta_i^L a_i^{L-1} = \underline{a_i^{L-1}(a_i^L-t_i)}
\end{equation}
or substituting $L$ into $o$ for our case with one hidden layer and the output layer $L$ we have 
\begin{equation}
    \nabla^o=\delta_i^o a_i^{h} = \underline{a_i^{h}(a_i^o-t_i)}
\end{equation}
but for our only hidden layer we have
\begin{equation}
    \nabla^h = \nabla^o (w^o)^T \sigma'(z^L) = \underline{\nabla^o (w^o)^T a^L(1-a^L)}
\end{equation}
and the gradients for the biases will be
\begin{align}
    \nabla_k^o &= \underline{\sum_i \delta_{ik}^o}
    \\ \nabla_k^h &= \underline{\sum_i \delta_{ik}^h}
\end{align}

In [467]:
def analytic_error(target):
    """Analytical output layer error"""

    def func(a):
        return a - target

    return func


analy_grad = analytic_error(target)

### Using automatic differentiation for the gradient

In [468]:
def dsigmoid_dx(a):
    """Rewritten derivative of sigmoid function"""
    return a * (1 - a)


def automatic_error(target):
    """Automatic output layer error"""
    dCda_L = grad(cost_log_reg(target))

    def func(a):
        return dsigmoid_dx(a) * dCda_L(a)

    return func


auto_grad = automatic_error(target)

# Compare analytical vs automatic with target predictions
print(analy_grad(probabilities))
print()
print(auto_grad(probabilities))

[[ 0.50662492]
 [-0.4252487 ]
 [-0.46931083]
 [ 0.60044713]]

[[ 0.50662494]
 [-0.42524868]
 [-0.46931082]
 [ 0.6004471 ]]


### Back propagation
The results are the same, so I use the analytical expression since it is faster than using autograd each run.

Since we only have one hidden layer we need to propogate only once from the output layer to the first hidden layer

In [469]:
# Choose gradient method
error_func = analy_grad


def back_propagate(X):
    """Back propagation algorithm for one hidden layer"""
    z_h, a_h, z_o, probabilities = feed_forward(X)

    # Output layer error delta^L
    error_o = error_func(probabilities)

    # Hidden layer error delta^1
    error_h = error_o @ output_weights.T * dsigmoid_dx(a_h)

    # Gradients for the hidden layer
    hidden_weights_gradient = X.T @ error_h
    hidden_bias_gradient = np.sum(error_h, axis=0)

    # Gradients for the output layer
    output_weights_gradient = a_h.T @ error_o
    output_bias_gradient = np.sum(error_o, axis=0)

    return hidden_weights_gradient, hidden_bias_gradient, output_weights_gradient, output_bias_gradient

### Iterating until convergence

In [470]:
eta = 0.5  # learning rate
tol = 1e-7  # convergence check tolerance 
n_epochs = 1000  # max number of epochs 

for i in range(n_epochs):
    # Feed forward and back propagate back to get all gradients for each epoch
    dWh, dBh, dWo, dBo = back_propagate(X)
    
    # Update weights and biases
    output_weights -= eta * dWo
    output_bias -= eta * dBo
    hidden_weights -= eta * dWh
    hidden_bias -= eta * dBh

print("After back propagation:\n")
print("Output weights and bias:")
print(output_weights)
print(output_bias)

print()
print("Hidden weights and bias:")
print(hidden_weights)
print(hidden_bias)

print("\nTarget")
print(target)
print("\nProbabilities:")
probabilities = feed_forward(X)[-1]
print(probabilities)
print("\nPrediction")
print(predict(probabilities))

After back propagation:

Output weights and bias:
[[-7.03235395]
 [ 7.5889668 ]]
[-0.55613141]

Hidden weights and bias:
[[ 8.5189733   8.54247513]
 [-4.14780657  4.89743741]]
[ 2.64258752 -1.4108913 ]

Target
[[0]
 [1]
 [1]
 [0]]

Probabilities:
[[0.00356487]
 [0.99604986]
 [0.4986298 ]
 [0.50168888]]

Prediction
[[0]
 [1]
 [0]
 [1]]


We get the correct result for both the OR and the AND gates, however the XOR gate we do not get the correct prediction. 

[PLOT ACCURACY AS FUNCTION OF LEARNING RATE]